security:
  oauth2:
    client:
      client-id: 78qmxrh8dmjhui
      client-secret: iEtvacldJbT0jIFN
      access-token-uri: https://www.linkedin.com/oauth/v2/accessToken   
      user-authorization-uri: https://www.linkedin.com/oauth/v2/authorization
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
    resource:
      user-info-uri: https://api.linkedin.com/v1/people/~?format=json