security:
  oauth2:
    client:
      clientId: 78qmxrh8dmjhui
      clientSecret: iEtvacldJbT0jIFN
      accessTokenUri: https://www.linkedin.com/oauth/v2/accessToken   
      userAuthorizationUri: https://www.linkedin.com/oauth/v2/authorization
      redirect-uri: https://www.google.com/
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.linkedin.com/v1/people/~?format=json